### ISSUE TITLE
Error: Comment for stack is too long

### ISSUE THREAD

**Issue by lucasmaia1202** [corymhall/cdk-diff-action#67]
Error commenting stages:  Error: Comment for stack elt-dev is too long, please report this as a bug https://github.com/corymhall/cdk-diff-action/issues/new
Error: Comment for stack elt-dev is too long, please report this as a bug https://github.com/corymhall/cdk-diff-action/issues/new
    at StageProcessor.commentStacks (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/stage-processor.js:95:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at StageProcessor.commentStages (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/stage-processor.js:126:1)
    at run (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/action.js:[63](https://github.com/Zephyr-Home/data-engine/actions/runs/10097914537/job/27923829397?pr=132#step:9:64):1)
Error performing diff:  Error: Comment for stack elt-dev is too long, please report this as a bug https://github.com/corymhall/cdk-diff-action/issues/new
    at StageProcessor.commentStacks (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/stage-processor.js:95:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at StageProcessor.commentStages (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/stage-processor.js:126:1)
    at run (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/lib/action.js:63:1)

**Comment by corymhall** [comment]
@lucasmaia1202 looks like you may be running into https://github.com/corymhall/cdk-diff-action/issues/34. I'm going to close this one as a duplicate.
