### ISSUE TITLE
Unable to assume role when referencing AWS GovCloud region

### ISSUE THREAD

**Issue by mdillard-foreflight** [corymhall/cdk-diff-action#70]
I'm hitting an error assuming a role to perform the diff, and it is because I am pointing at an AWS GovCloud region.

AWS GovCloud regions use a different partition than "standard" AWS regions, which means ARNs need to be built a little differently (see [here](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html) and [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html)).

This line hardcodes the partition as `aws`, but in a GovCloud region, this should use `aws-us-gov` instead:

https://github.com/corymhall/cdk-diff-action/blob/d2af87dba62e992232cd7d376456ff506f7d39c0/src/diff.ts#L77

Here is a sample error, with some identifying information elided.

```
Error performing stack diff:  AccessDenied: User: arn:aws-us-gov:sts::123456789000:assumed-role/SomeRoleName is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789000:role/cdk-hnb659fds-lookup-role-123456789000-us-gov-west-1
    at throwDefaultError (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/smithy-client/dist-cjs/index.js:839:1)
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/smithy-client/dist-cjs/index.js:848:1
Error: User: arn:aws-us-gov:sts::123456789000:assumed-role/SomeRoleName is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::072307168900:role/cdk-hnb659fds-lookup-role-123456789000-us-gov-west-1
    at de_CommandError (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:476:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:1
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/core/dist-cjs/index.js:165:1
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/middleware-retry/dist-cjs/index.js:3[20](https://github.com/myrepo/actions/runs/123/job/456?pr=6364#step:5:21):1
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:1
    at /home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@aws-sdk/credential-providers/dist-cjs/fromTemporaryCredentials.js:50:1
    at coalesceProvider (/home/runner/work/_actions/corymhall/cdk-diff-action/v1/node_modules/@smithy/core/dist-cjs/index.js:288:1) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: '7578410a-fb2a-42fc-8ede-0fc2d6fae668',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'Sender',
  Code: 'AccessDenied'
}
```

I believe the answer is straight-forward: detect whether the target region starts with `us-gov-*`, and if it does, set the partition to `aws-us-gov` instead of `aws`.

**Comment by mdillard-foreflight** [comment]
I'll try to come up with a PR shortly to make it easy to slide this in.
